version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - errorlint
    # - gosec
    - misspell
    - revive
    # - funcorder
    - modernize
  settings:
    errcheck:
      check-type-assertions: true
    misspell:
      locale: US
    revive:
      rules:
        - name: unexported-return
          disabled: true
  exclusions:
    presets:
      - common-false-positives
      - std-error-handling

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/babarot/gomi
