version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w
      - -X main.version=v{{.Version}}
      - -X main.revision={{.ShortCommit}}
      - -X main.buildDate={{.CommitDate}}
    main: .
    flags:
      - -trimpath

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  prerelease: auto
  draft: false
  footer: >-
    ### Installation

    - [Homebrew](https://brew.sh/): `brew install babarot/tap/gomi`
    - [Scoop](https://scoop.sh/): `scoop install gomi`

    ---
    Generated by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - repository:
      owner: babarot
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://gomi.dev
    description: A Safer Alternative to the UNIX rm Command!
    license: MIT
    url_template: "https://github.com/babarot/gomi/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

scoops:
  - repository:
      owner: babarot
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    homepage: https://gomi.dev/
    description: "🗑️ Your UNIX rm command with a safety net!"
    license: MIT
    url_template: "https://github.com/babarot/gomi/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: github-actions
      email: github-actions@github.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
