project_name: gomi
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gomi
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# https://goreleaser.com/customization/#Homebrew
brews:
- name: gomi
  tap:
    owner: b4b4r07
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/b4b4r07/gomi
  description: Replacement for UNIX rm command!
  skip_upload: auto
  test: |
    system "#{bin}/gomi", "--version"
