name: Labels
on: pull_request

jobs:
  triage:
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/labeler@v5
        with:
          sync-labels: true
