name: Label Sync

on:
  push:
    branches:
      - main
    paths:
      - .github/label-definitions.yaml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Sync labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: .github/label-definitions.yaml
          delete-other-labels: true
